name: Test Action

on:
  push:
    branches:
      - main
      - VJalili-patch-31
    paths:
      - 'src/**'
      - 'dockerfiles/**'
      - 'scripts/docker/build_docker.py'
      - '.github/workflows/test_action.yml'
  pull_request:
    branches:
      - main
      - VJalili-patch-31
    paths:
      - 'src/**'
      - 'dockerfiles/**'
      - 'scripts/docker/build_docker.py'
      - '.github/workflows/test_action.yml'

env:
  AZURE_STORAGE_ACCOUNT_NAME: 'cromwell7379410456f0'
  AZURE_STORAGE_CONTAINER_NAME: 'workflows'
  WORKFLOW_PATH: "https://cromwell7379410456f0.blob.core.windows.net/tests-inputs/Aaa.wdl"
  WORKFLOW_INPUTS_PATH: "https://cromwell7379410456f0.blob.core.windows.net/tests-inputs/aaa_test_inputs.json"
  WORKFLOW_DEPENDENCIES_PATH: "https://cromwell7379410456f0.blob.core.windows.net/tests-inputs/test_wdls.zip"

permissions:
  id-token: write
  contents: write

jobs:
  build_args_job:
    runs-on: ubuntu-latest
    environment: Tests
    name: TEST RUN
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            
      - name: Submit workflow
        id: submit
        uses: Genometric/hello-world-javascript-action@dev-20240711-2838096
        with:
          azure-storage-account-name: ${{ env.AZURE_STORAGE_ACCOUNT_NAME }}
          azure-storage-container-name: ${{ env.AZURE_STORAGE_CONTAINER_NAME }}
          workflow-path: ${{ env.WORKFLOW_PATH }}
          workflow-inputs-path: ${{ env.WORKFLOW_INPUTS_PATH }}
          workflow-dependencies-path: ${{ env.WORKFLOW_DEPENDENCIES_PATH }}
          subcommand: "submit"
      - name: Monitor submission status
        id: monitor
        uses: Genometric/hello-world-javascript-action@dev-20240711-2838096
        with:
          azure-storage-account-name: ${{ env.AZURE_STORAGE_ACCOUNT_NAME }}
          azure-storage-container-name: ${{ env.AZURE_STORAGE_CONTAINER_NAME }}
          workflow-path: ${{ env.WORKFLOW_PATH }}
          workflow-inputs-path: ${{ env.WORKFLOW_INPUTS_PATH }}
          workflow-dependencies-path: ${{ env.WORKFLOW_DEPENDENCIES_PATH }}
          workflow-id: ${{ steps.submit.outputs.workflowId }}
          subcommand: "monitor"
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"


