name: Test Action

on:
  push:
    branches:
      - main
      - VJalili-patch-31
    paths:
      - 'src/**'
      - 'dockerfiles/**'
      - 'scripts/docker/build_docker.py'
      - '.github/workflows/test_action.yml'
  pull_request:
    branches:
      - main
      - VJalili-patch-31
    paths:
      - 'src/**'
      - 'dockerfiles/**'
      - 'scripts/docker/build_docker.py'
      - '.github/workflows/test_action.yml'

jobs:
  build_args_job:
    runs-on: ubuntu-latest
    name: TEST RUN
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - name: Hello world action step
        id: hello
        uses: Genometric/hello-world-javascript-action@v1.3
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
